choco install google-chrome-x64 -y
choco install mumble -y
choco install filezilla -y
choco install puttyTray -y
choco install git -y
choco install teamspeak -y
choco install steam -y
choco install utorrent -y
choco install battle.net -y
choco install 7zip -y
choco install javaruntime -y
choco install teamviewer -y
choco install SublimeText3 -y
choco install wireshark -y
choco install googledrive -y
choco install spotify -y
choco install discord -y
choco install sharex -y
choco install vmwarevsphereclient -y
choco install jre8 -y
choco install foobar2000 -y
choco install dropbox -y
choco install veracrypt -y
choco install vim -y
choco install github -y
choco install lastpass -y
choco install openvpn -y
choco install firefox -y
choco install lastpass-for-applications -y
choco install tor-browser -y
choco install windows-tweaker -y
choco install mpc-hc -y
choco install python2 -y

pause
